"""Central window, grid, and rendering configuration."""

COLUMNS = 32
ROWS = 24
CELL_SIZE = 20

WINDOW_WIDTH = COLUMNS * CELL_SIZE
WINDOW_HEIGHT = ROWS * CELL_SIZE
WINDOW_TITLE = "Snake Game"
FPS = 60
SNAKE_MOVE_INTERVAL_MS = 125

BACKGROUND_COLOR = (0, 0, 0)
GRID_COLOR = (50, 50, 50)
SNAKE_COLOR = (60, 200, 80)
FOOD_COLOR = (230, 80, 60)
